packages:
  - playground
  - src
  - test/fixtures/*
allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  protobufjs: false
catalog:
  '@azure/monitor-opentelemetry': 1.19.0
  '@azure/monitor-opentelemetry-exporter': 1.0.0-beta.32
  '@microlabs/otel-cf-workers': 1.0.0-rc.52
  '@nuxt/nitro-server': ^4.4.4
  '@nuxt/schema': ^4.5.2
  '@opentelemetry/api': ^1.9.1
  '@opentelemetry/auto-instrumentations-node': ^0.79.0
  '@opentelemetry/context-async-hooks': ^2.10.0
  '@opentelemetry/instrumentation': ^0.221.0
  '@opentelemetry/instrumentation-http': ^0.221.0
  '@opentelemetry/instrumentation-undici': ^0.31.0
  '@opentelemetry/resources': ^2.10.0
  '@opentelemetry/sdk-metrics': ^2.10.0
  '@opentelemetry/sdk-node': ^0.221.0
  '@opentelemetry/sdk-trace-base': ^2.10.0
  '@opentelemetry/sdk-trace-node': ^2.10.0
  '@opentelemetry/semantic-conventions': ^1.43.0
  '@types/node': ^22.20.1
  '@vitest/coverage-v8': ^4.1.10
  '@vitest/ui': ^4.1.10
  automd: ^0.4.3
  changelogen: ^0.6.2
  consola: ^3.4.2
  defu: ^6.1.7
  eslint: ^9.39.5
  eslint-config-unjs: ^0.6.2
  estree-walker: ^3.0.3
  exsolve: ^1.1.1
  h3: ^1.15.11
  jiti: ^2.7.0
  magic-string: ^1.2.0
  mlly: ^1.8.2
  nitro-test-utils: ^3.0.2
  nitropack: ^2.13.4
  pathe: ^2.0.3
  rollup: ^4.62.4
  typescript: ^5.9.3
  unbuild: ^3.6.1
  unimport: ^6.4.0
  vitest: ^4.1.10
